version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j3q6m8n2
      - REPOSITORY_URI=public.ecr.aws/j3q6m8n2/angular-build-demo
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Building the Angular app...
      - npm run build
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
     

  post_build:
    commands:
      - echo Building the Docker image...
      - echo Pushing the Docker images...
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
       # Give your container name
      - DOCKER_CONTAINER_NAME=angular-build-demo
      - echo $DOCKER_CONTAINER_NAME
      - printf '[{"name”:"__ECS_CONTAINER_NAME__","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Writing image definitions file...
      - cat imagedefinitions.json

artifacts:
files: imagedefinitions.json