version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the Angular app...
      - npm run build -- --prod
  post_build:
    commands:
      - echo Building the Docker image...
      - docker build -t angularlb .
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j3q6m8n2
      - echo Pushing the Docker image to Amazon ECR...
      - docker tag angularlb:latest public.ecr.aws/j3q6m8n2/angularlb:latest
      - docker push public.ecr.aws/j3q6m8n2/angularlb:latest